services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
    init: true

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: on-failure
    init: true

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: on-failure
    init: true

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/db/wordpress'
  mariadb:
    name: mariadb-data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/db/mariadb'